fail_fast: false
repos:
    -   repo: https://github.com/pocc/pre-commit-hooks
        rev: v1.3.5
        hooks:
            # -   id: clang-format
            #     args: [--style=Google]
            # -   id: clang-tidy
            # -   id: uncrustify
            # -   id: cppcheck
            -   id: cpplint
                args: ["--filter=-legal/copyright", "--exclude=runners/*.pb.cc"]
            # -   id: include-what-you-use
    -   repo: https://github.com/BlankSpruce/gersemi
        rev: 0.8.2
        hooks:
            -   id: gersemi