#ifndef SRC_DESTINATIONS_REDISDESTINATION_HPP_
#define SRC_DESTINATIONS_REDISDESTINATION_HPP_

namespace CavaThor {

class RedisDestination {
};

}  // CavaThor

#endif  // SRC_DESTINATIONS_REDISDESTINATION_HPP_
